### ISSUE TITLE
ModuleNotFoundError: No module named 'sahi.model'

### ISSUE THREAD

**Issue by r-matsuzaka** [Lightning-AI/lightning-flash#1481]
## 🐛 Bug

I just want to run tutorial [here](https://lightning-flash.readthedocs.io/en/stable/reference/instance_segmentation.html).

### Environment
- Ubuntu Desktop 22.04 LTS
- GPU RTX2080
- Driver nvidia-driver-510

### To Reproduce

- Dockerfile
```
FROM nvidia/cuda:11.6.0-cudnn8-devel-ubuntu20.04

# https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes
ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y python3 python3-pip \
&& apt-get install ffmpeg libsm6 libxext6  -y

RUN pip3 install --no-cache-dir \
   jupyterlab \
   lightning-flash[image] \
   icedata \
   icevision
```

- docker-compose.yaml
```
version: "3"
services:
  notebook:
    build: .
    volumes:
      - ".:/home/work"
      - ".jupyter:/root/.jupyter"
    ports:
      - "7777:7777"
    tty: true
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
       resources:
         reservations:
           devices:
             - capabilities:
               - gpu
    command: jupyter lab --ip=0.0.0.0 --port=7777 --allow-root --no-browser --NotebookApp.token=''
```

Then, run
```
docker compose up
```

Connect to `localhost:7777` and open up jupyter.

Then, run
```
from functools import partial

import flash
from flash.core.utilities.imports import example_requires
# from flash.image import InstanceSegmentation, InstanceSegmentationData

example_requires("image")

import icedata  # noqa: E402
```

I got the error

> ModuleNotFoundErrorTraceback (most recent call last)
> Cell In [3], line 9
>       5 # from flash.image import InstanceSegmentation, InstanceSegmentationData
>       7 example_requires("image")
> ----> 9 import icedata  # noqa: E402
> 
> File /usr/local/lib/python3.8/dist-packages/icedata/__init__.py:1
> ----> 1 import icedata.utils
>       2 import icedata.template
>       4 from icedata.utils import *
> 
> File /usr/local/lib/python3.8/dist-packages/icedata/utils/__init__.py:1
> ----> 1 from icedata.utils.utils import *
>       2 from icedata.utils.plot_size_histogram import *
> 
> File /usr/local/lib/python3.8/dist-packages/icedata/utils/utils.py:3
>       1 __all__ = ["load_model_weights_from_url", "load_data"]
> ----> 3 from icevision.all import *
>       6 def load_model_weights_from_url(
>       7     model: nn.Module, url: str, map_location=torch.device("cpu"), **kwargs
>       8 ) -> None:
>       9     state_dict = torch.hub.load_state_dict_from_url(
>      10         url, map_location=map_location, **kwargs
>      11     )
> 
> File /usr/local/lib/python3.8/dist-packages/icevision/__init__.py:7
>       5 from icevision.data import *
>       6 from icevision import backbones
> ----> 7 from icevision import models
>       8 from icevision.metrics import *
>       9 from icevision.visualize import *
> 
> File /usr/local/lib/python3.8/dist-packages/icevision/models/__init__.py:32
>      29     from icevision.models import fastai
>      31 if SoftDependencies.sahi:
> ---> 32     from icevision.models import inference_sahi
> 
> File /usr/local/lib/python3.8/dist-packages/icevision/models/inference_sahi.py:14
>      10 from icevision.visualize.utils import *
>      11 from icevision.tfms.albumentations import albumentations_adapter
> ---> 14 from sahi.model import DetectionModel
>      15 from sahi.prediction import ObjectPrediction
>      16 from sahi.predict import get_sliced_prediction as sahi_get_sliced_prediction
> 
> ModuleNotFoundError: No module named 'sahi.model'
